# Note that we're using this version since it supports the "extends"
# construct.  Otherwise we'd have to copy the configurations from
# nf-devstack
version: "2.1"
services:
  nf-client-webpack:
    container_name: nf-client-webpack
    extends:
      file: docker-compose.nf-devstack.yml
      service: nf-shell
    ports:
      - 8080:8080
    entrypoint:
      /noteflight/webapp/devbin/nf-run-client-webpack

  nf-rails-server:
    container_name: nf-rails-server
    extends:
      file: docker-compose.nf-devstack.yml
      service: nf-shell
    ports:
      - 3000:3000
    entrypoint:
      /noteflight/webapp/devbin/nf-run-rails-server

  nf-gulp:
    container_name: nf-gulp
    extends:
      file: docker-compose.nf-devstack.yml
      service: nf-shell
    entrypoint:
      /noteflight/webapp/devbin/nf-run-gulp

  nf-speedyg:
    container_name: nf-speedyg
    extends:
      file: docker-compose.nf-devstack.yml
      service: nf-shell
    entrypoint:
      /noteflight/webapp/devbin/nf-run-speedyg
networks:
  host:
