version: "2.1"
services:
  elasticsearch:
    container_name: elasticsearch
    image: nf-devstack-elasticsearch
    environment:
      ES_JAVA_OPTS: -Xms256m -Xmx256m
    ports:
      - 9200:9200
      - 9300:9300
    networks:
      - host
    volumes:
      - ${NF_DEVSTACK_DATA}/elasticsearch:/home/elasticsearch/elasticsearch/data
    restart: always
  elasticsearch-test:
    container_name: elasticsearch-test
    image: nf-devstack-elasticsearch
    environment:
      ES_JAVA_OPTS: -Xms256m -Xmx256m
    ports:
      - 9201:9200
      - 9301:9300
    networks:
      - host
    volumes:
      - ${NF_DEVSTACK_DATA}/elasticsearch-test:/home/elasticsearch/elasticsearch/data
    restart: always
  dynamodb:
    container_name: dynamodb
    image: nf-devstack-dynamodblocal
    ports:
      - 8000:8000
    networks:
      - host
    volumes:
      - ${NF_DEVSTACK_DATA}/dynamodb:/home/dynamodblocal/data
    restart: always
  mysql:
    container_name: mysql
    image: mysql:5.7.35
    environment:
      MYSQL_ROOT_PASSWORD: newpassword
    ports:
      - 3306:3306
    networks:
      - host
    volumes:
      - ${NF_DEVSTACK_DATA}/mysql:/var/lib/mysql
    restart: always
  nf-shell:
    container_name: nf-shell
    image: nf-devstack-shell-local
    environment:
      NF_DEVTEST_DATABASE_USER: "root"
      NF_DEVTEST_DATABASE_PASSWORD: "newpassword"
      NF_DEVTEST_DATABASE_HOST: "172.17.0.1"
      NF_DEVTEST_DATABASE_PORT: "3306"
      NF_DEVTEST_DYNAMODB_HOST: "172.17.0.1"
      NF_DEVTEST_DYNAMODB_PORT: "8000"
      NF_DEV_ELASTICSEARCH_HOST: "172.17.0.1"
      NF_DEV_ELASTICSEARCH_PORT: "9200"
      NF_TEST_ELASTICSEARCH_HOST: "172.17.0.1"
      NF_TEST_ELASTICSEARCH_PORT: "9201"
      NF_DEV_WEBSERVER_HOST: ${NF_DEV_WEBSERVER_HOST}
      NF_DEV_WEBSERVER_PORT: 8080
    networks:
      - host
    volumes:
      # Allows docker commands to be run from within the container
      - /var/run/docker.sock:/var/run/docker.sock
      # Mount the noteflight repos
      - ${NF_REPOS}:/noteflight
      # Set the mock_s3 data to go to the devstack data directory
      - ${NF_DEVSTACK_DATA}/nf-site-mock_s3:/noteflight/webapp/site/public/mock_s3
      # Mount files from the user's home directory
      - ${NF_DEVSTACK_USER_DIR}/.aws:/home/${NF_DEVSTACK_USER}/.aws
      - ${NF_DEVSTACK_USER_DIR}/.gitconfig:/home/${NF_DEVSTACK_USER}/.gitconfig
      - ${NF_DEVSTACK_USER_DIR}/.netrc:/home/${NF_DEVSTACK_USER}/.netrc
      - ${NF_DEVSTACK_USER_DIR}/.ssh:/home/${NF_DEVSTACK_USER}/.ssh
    entrypoint:
      /noteflight/webapp/devbin/nf-noop-loop
networks:
  host:
